[package]
name = "csm"
version = "0.1.0"
edition = "2024"

[lints.clippy]
all = "deny"

[features]
default = ["__test_bash"]  # Don't assume devs have other shells installed
__test_bash = []
__test_fish = []
__test_powershell = []
__test_zsh = []

[dependencies]
bzip2 = "0.6.1"
clap = { version = "4.5.50", features = ["derive", "wrap_help"] }
clap_complete = "4.5.60"
dirs = "6.0.0"
env_logger = "0.11.8"
log = "0.4.28"
reqwest = { version = "0.12.24", default-features = false, features = ["http2", "charset", "system-proxy", "blocking", "rustls-tls-native-roots"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml_ng = "0.10.0"
sysinfo = "0.37.2"
tar = "0.4.44"

[target.'cfg(windows)'.dependencies]
windows-registry = "0.6.1"

[dev-dependencies]
assert_cmd = "2.0"
clap_builder = "4.5.51"
predicates = { version = "3.0", features = ["regex"] }
regex = "1.12.2"
temp-env = "0.3.6"
tempfile = "3.0"
which = "8.0.0"
